shosho/urls.py
from django.urls import path
from .views import (Dislike, PostListView, PostDetailView,PostEditView,PostDeleteView,
                    CommentDeleteView,ProfileView,ProfileEditView,AddFollower,
                    RemoveFollower,AddLike,UserSearch,ListFollowers,
                    AddCommentLike,DislikeComment,CommentReplyView,
                    PostNotification,FollowNotification,RemoveNotification,
                    CreateThread,ListThreads,ThreadView,CreateMessage,
                    ThreadNotification,SharedPostView,Explore)


urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('explore/',Explore.as_view(),name='explore'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/share', SharedPostView.as_view(), name='share-post'),
    path('post/edit/<int:pk>',PostEditView.as_view(),name='post-edit'),
    path('post/delete/<int:pk>',PostDeleteView.as_view(),name='post-delete'),
    path('post/<int:post_pk>/comment/<int:pk>/delete',CommentDeleteView.as_view(),name='comment-delete'),
    path('post/<int:post_pk>/comment/<int:pk>/like',AddCommentLike.as_view(),name='like-comment'),
    path('post/<int:post_pk>/comment/<int:pk>/dislike',DislikeComment.as_view(),name='dislike-comment'),
    path('post/<int:post_pk>/comment/<int:pk>/reply',CommentReplyView.as_view(),name='reply-comment'),
    path('post/<int:pk>/like',AddLike.as_view(),name='like'),
    path('post/<int:pk>/dislike',Dislike.as_view(),name='dislike'),
    path('profile/<int:pk>/',ProfileView.as_view(),name='profile'),
    path('profile/edit/<int:pk>/',ProfileEditView.as_view(),name='profile-edit'),
    path('profile/<int:pk>/followers/add',AddFollower.as_view(),name='add-follower'),
    path('profile/<int:pk>/followers/remove',RemoveFollower.as_view(),name='remove-follower'),
    path('profile/<int:pk>/followers/',ListFollowers.as_view(),name='list-follower'),
    path('search/',UserSearch.as_view(),name='profile-search'),
    path('notification/<int:notification_pk>/post/<int:post_pk>',PostNotification.as_view(),name='post-notification'),
    path('notification/<int:notification_pk>/profile/<int:profile_pk>',FollowNotification.as_view(),name='follow-notification'),
    path('notification/<int:notification_pk>/thread/<int:pk>',ThreadNotification.as_view(),name='thread-notification'),
    path('notification/delete/<int:notification_pk>',RemoveNotification.as_view(),name='notification-delete'),
    path('inbox/',ListThreads.as_view(),name='inbox'),
    path('inbox/create-thread',CreateThread.as_view(),name='create-thread'),
    path('inbox/<int:pk>',ThreadView.as_view(),name='thread'),
    path('inbox/<int:pk>/send',CreateMessage.as_view(),name='create-message'),


]

shoshomedia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),    
    path('shosho/',include('shosho.urls')),
    path('accounts/', include('allauth.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shosho/models.py
from distutils.command.upload import upload
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(User,blank=True,related_name='likes')
    dislikes = models.ManyToManyField(User,blank=True,related_name='dislikes')
    image = models.ManyToManyField('Image',blank=True)
    shared_body = models.TextField(blank=True,null=True)
    shared_on = models.DateTimeField(blank=True,null=True)
    shared_user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True,related_name='+')
    tags = models.ManyToManyField('Tag',blank=True)

    class Meta:
        ordering = ['-created_on','-shared_on']

    def __str__(self) -> str:
        return f'{self.body[:20]}... {self.id}'

    def create_tags(self):
        for word in self.body.split():
            if word[0] == '#':
                tag = Tag.objects.filter(name=word[1:]).first()
                if tag:
                    self.tags.add(tag.pk)
                else:
                    tag = Tag(name=word[1:])
                    tag.save()
                    self.tags.add(tag.pk)
                self.save()
        if self.shared_body:
            for word in self.shared_body.split():
                if word[0] == '#':
                    tag = Tag.objects.filter(name=word[1:]).first()
                    if tag:
                        self.tags.add(tag.pk)
                    else:
                        tag = Tag(name=word[1:])
                        tag.save()
                        self.tags.add(tag.pk)
                    self.save()


class Comment(models.Model):
    comment = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey('Post',on_delete=models.CASCADE)
    likes = models.ManyToManyField(User,blank=True,related_name='comment_likes')
    dislikes = models.ManyToManyField(User,blank=True,related_name='comment_dislikes')
    image = models.ImageField(upload_to='uploads/comment_pic',blank=True,null=True)
    parent = models.ForeignKey('self',on_delete=models.CASCADE,blank=True,null=True,related_name='+')

    def create_tags(self):
        for word in self.comment.split():
                if word[0] == '#':
                    tag = Tag.objects.filter(name=word[1:]).first()
                    if tag:
                        self.tags.add(tag.pk)
                    else:
                        tag = Tag(name=word[1:])
                        tag.save()
                        self.tags.add(tag.pk)
                    self.save()

    @property
    def children(self):
        return Comment.objects.filter(parent=self).order_by('-created_on').all()
    
    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False

class Profile(models.Model):
    user = models.OneToOneField(User,primary_key=True,verbose_name='user',related_name='profile',on_delete=models.CASCADE)
    name = models.CharField(max_length=150,blank=True,null=True)
    bio = models.TextField(max_length=750,blank=True,null=True)
    birth_date = models.DateField(null=True,blank=True)
    location = models.CharField(max_length=150,blank=True,null=True)
    picture = models.ImageField(upload_to = 'uploads/profile_pictures',default ='uploads/profile_pictures/default.png',blank=True)
    followers = models.ManyToManyField(User,blank=True,related_name='followers')

    def __str__(self) -> str:
        return self.name.title()

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created, **kwargs):
    if created:
        user = instance
        Profile.objects.create(user=user,
                                name = user.username
                                )


@receiver(post_save,sender=User)
def save_user_profile(sender,instance, **kwargs):
    instance.profile.save()


class Notification(models.Model):
    # 1 - Like 2 - Comment 3- Follow
    notification_type = models.IntegerField()
    to_user = models.ForeignKey(User,related_name='notification_to',on_delete=models.CASCADE,null=True)
    from_user = models.ForeignKey(User,related_name='notification_from',on_delete=models.CASCADE,null=True)
    post = models.ForeignKey('Post',related_name='+',on_delete=models.CASCADE,blank=True,null=True)
    comment = models.ForeignKey('Comment',related_name='+',on_delete=models.CASCADE,blank=True,null=True)
    date = models.DateTimeField(default=timezone.now)
    user_has_seen = models.BooleanField(default=False)
    thread = models.ForeignKey('ThreadModel',on_delete=models.CASCADE,related_name='+',blank=True,null=True)

class ThreadModel(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='+')
    receiver = models.ForeignKey(User,on_delete=models.CASCADE,related_name='+')

class Message(models.Model):
    thread = models.ForeignKey('ThreadModel',on_delete=models.CASCADE,related_name='+',blank=True,null=True)
    sender_user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='+')
    receiver_user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='+')
    body = models.CharField(max_length=1000)
    image = models.ImageField(upload_to='uploads/message_pic',blank=True,null=True)
    date = models.DateTimeField(default=timezone.now)
    is_read = models.BooleanField(default=False)

class Image(models.Model):
    image = models.ImageField(upload_to='uploads/post_pic',blank=True,null=True)

class Tag(models.Model):
    name = models.CharField(max_length=300)
    

shosho/forms.py
from django import forms
from django.dispatch import receiver
from pkg_resources import require
from .models import Message, Post,Comment, ThreadModel

class PostForm(forms.ModelForm):
    body = forms.CharField(label='',widget=forms.Textarea(attrs={
        'rows':3,
        'placeholder':'Post Something...'
    }))

    image = forms.ImageField(required=False,widget=forms.ClearableFileInput(attrs={
        'multiple':True
    }))

    class Meta:
        model = Post
        fields = ['body']
    


class CommentForm(forms.ModelForm):
    comment = forms.CharField(label='',widget=forms.Textarea(attrs={
        'rows':3,
        'placeholder':'Comment Something...Anything...'
    }))

    image = forms.ImageField(required=False)

    class Meta:
        model = Comment
        fields = ['comment','image']

class ThreadForm(forms.Form):
    username = forms.CharField(label='',max_length=100)

class MessageForm(forms.ModelForm):
    body = forms.CharField(label='',max_length=1000)
    image = forms.ImageField(required=False)

    class Meta:
        model = Message
        fields = ['body','image']

class ShareForm(forms.Form):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows':'3',
            'placeholder':'Post Something....',
        })
    )

class ExploreForm(forms.Form):
    query = forms.CharField(label='',
    widget=forms.TextInput(attrs={
        'placeholder':'Explore Tags'
    }))

shosho/templates/shosho/comment_delete.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
   <div class="container">
        <div class="row mt-5">
            <div class="col-md-5 col-sm-6">
                <a href="{% url 'post-detail' object.post.pk %}" class="btn btn-light"> Back to Post</a>
            </div>
        </div>

       <div class="row justify-content-center mt-3">
           <div class="col-md-5 col-sm-12 border-bottom">
                   <form action="" method="POST">
                       {% csrf_token %}
                       <h4>Are you sure??</h4>
                       <h5>You are about to delete this comment, this cannot be undone.</h5>
                       {{form | crispy}}
                       <div class="d-grid gap-2">
                           <button class='btn btn-danger  mt-4 mb-4'>Delete</button>
                       </div>
                   </form>
           </div>
       </div>

   </div>
{% endblock content %}

shosho/templates/shosho/create_thread.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">

    <div class="row">
        <div class="col-md-12 p-5">
            <a href="{% url 'inbox' %}" class='btn btn-light'> Back to your Inbox </a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 p-5">
            <h3>Start a Convo</h3>
        </div>
    </div>

    <div class="row justify-content mt-3 mb-5">
        <div class="col-md-5 col-sm-12">
            {% if messages %}
                {% for message in messages  %}
                    <div class="alert alert-danger">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                <p>Enter the Person you would like to chat with</p>
                {{ form | crispy }}
                <div class="d-grid gap-2">
                    <button class="btn btn-dark mt-3" type="submit">
                        Continue
                    </button>
                </div>
            </form>
        </div>
    </div>

</div>

{% endblock content %}

shosho/templates/shosho/explore.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row mt-5">
        <div class="col-md-3 col-sm-6 border-bottom">
            <a href="{% url 'post-list' %}" class="btn btn-light">Back to Feed</a>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12">
            {% if tag %}
                <h3>Explore #{{tag.name}} posts</h3>
                <p class="mb-3">Most recent post tagged with {{tag.name}}</p>
            {% else %}
            <h3>Explore Post</h3>
            <p class="mb-3">Explore tags to find posts</p>
            {% endif %}

            <form action="" method="POST" class="mb-5">
                {% csrf_token %}
                {{explore_form | crispy}}
                <button class="btn btn-dark mt-3" type='submit'>Explore</button>
            </form>
        </div>
    </div>
    {% for post in posts %}
    <div class="row justify-content-center mt-3">
        <div class="col-md-8 col-sm-12 border-bottom ">
            {% if post.shared_user %}
            <div>
                <a href="{% url 'profile' post.shared_user.profile.pk %}">
                <img class = "rounded-circle post-img" src="{{post.shared_user.profile.picture.url}}" alt="Image">
                </a>
                <p class="post-text">
                    <a class="text-primary link-color" href="{% url 'profile' post.shared_user.profile.pk %}">
                    @{{post.shared_user}}</a> shared a post on  {{post.shared_on}}
                </p>
            </div>

            {% else %}
            
            <div>
                <a href="{% url 'profile' post.author.profile.pk %}">
                 {% if post.author.profile.picture.url %}
                <img class = "rounded-circle post-img" src="{{post.author.profile.picture.url}}" alt="Image">
                 {% endif %}
                </a>
                <p class="post-text">
                    <a class="text-primary link-color" href="{% url 'profile' post.author.profile.pk %}">
                    @{{post.author}}</a>  {{post.created_on}}
                    <span onclick="shareToggle('{{post.pk}}')"><i class="fa-solid fa-share-from-square share-btn"></i></span>
                </p>
            </div>
            {% endif %}
            <form action="{% url 'share-post' post.pk %}" method="POST" class='d-none' id="{{post.pk}}">
                {% csrf_token %}
                {{ share_form | crispy }}
                <div class="d-grid gap-2">
                    <button class="btn btn-dark mt-3"> Share Post..</button>
                </div>
            </form>

            {% if post.shared_body %}
            <div class="position-relative border-bottom mb-3 body">
                <p>{{post.shared_body}}</p>
                </div>

             <div class="shared-post">
                <a href="{% url 'profile' post.author.profile.pk %}">
                    <img class = "rounded-circle post-img" src="{{post.author.profile.picture.url}}" alt="Image">
                    </a>
                    <p class="post-text">
                        <a class="text-primary link-color" href="{% url 'profile' post.author.profile.pk %}">
                        @{{post.author}}</a>  {{post.created_on}}
                        {% comment %} <span onclick="shareToggle('{{post.pk}}')"><i class="fa-solid fa-share-from-square share-btn"></i></span> {% endcomment %}
                    </p>
            </div> 
            {% endif %}
                <div class="position-relative">
                    {% if post.image.count > 0 %}
                    <div class="row">
                        {% for img in post.image.all %}
                            <div class="col-md-4 col-xs-12">
                                <img src=" {{ img.image.url }} " class="post-image" />
                            </div>
                        {% endfor %}
                    </div>
                    {% endif %}

                <div class="body">
                    <p>{{post.body}}</p>
                </div>
           <a href="{% url 'post-detail' post.id %}" class="stretched-link"></a>
        </div>

        <div class="d-flex flex-row">
            <form action="{% url 'like' post.pk %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button class="remove-default-btn" type="submit">
                    <i class="fa-solid fa-thumbs-up"> <span>{{post.likes.all.count}}</span>  </i>
                </button>
            </form>

            <form action="{% url 'dislike' post.pk %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button class="remove-default-btn" type="submit">
                    <i class="fa-solid fa-thumbs-down"> <span>{{post.dislikes.all.count}}</span> </i>
                </button>
            </form>
        </div>
   </div>
    </div>
    {% endfor %}
</div>


{% endblock content %}

shosho/templates/shosho/follower_list.html
{% extends 'landing/base.html' %}

{% block content %}
   <div class="container">
        <div class="row mt-5">
            <div class="col-md-5 col-sm-6">
                <a href="{% url 'profile' profile.pk %}" class="btn btn-light"> Back to Profile</a>
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-md-5 col-sm-12">
                {% if profile.name %}
                    <h3> Followers for {{profile.name}}</h3>
                    {% else %}
                    <h3> Followers for @{{profile.user.username}}</h3>
                {% endif %}
            </div>
        </div>

        {% for follower in followers %}
        <div class="row justify-content-center">
            <div class="col-md-5 col-sm-12 position-relative my-3">
                <a href="{% url 'profile' follower.profile.pk %}"> <img class="rounded-circle post-img" height="60" width="60" src="{{follower.profile.picture.url}}" alt="" /> </a>
                <a href="{% url 'profile' follower.profile.pk %}" class="link-color"> <h5 class="mt-3">@{{follower.username}}</h5></a>

            </div>
        </div>
        {% endfor %}
    </div>

    {% endblock %}

shosho/templates/shosho/inbox.html
{% extends 'landing/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 p-5">
            <h3>Your Chats</h3>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12 p-5">
            <form action="{% url 'create-thread' %}" method="GET">
                <button class="btn btn-light p-3" type='submit'>Start a Conversation</button>
            </form>
        </div>
    </div>

    {% for thread in threads.all %}
        <div class="row mb-3">
            <div class="card col-md-12 p-5 shadow-sm">
                <h5> <i class="fa-solid fa-envelope"></i> @{{thread.user}} - @{{thread.receiver}} </h5>
                <a href="{% url 'thread' thread.pk %}" class="stretched-link"></a>
            </div>
        </div>
    {% endfor %}

</div>


{% endblock content %}

shosho/templates/shosho/post_delete.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
   <div class="container">
        <div class="row mt-5">
            <div class="col-md-5 col-sm-6">
                <a href="{% url 'post-detail' object.id %}" class="btn btn-light"> Back to Post</a>
            </div>
        </div>

       <div class="row justify-content-center mt-3">
           <div class="col-md-5 col-sm-12 border-bottom">
                   <form action="" method="POST">
                       {% csrf_token %}
                       <h4>Are you sure??</h4>
                       <h5>You are about to delete this post, this cannot be undone.</h5>
                       {{form | crispy}}
                       <div class="d-grid gap-2">
                           <button class='btn btn-danger  mt-4 mb-4'>Delete</button>
                       </div>
                   </form>
           </div>
       </div>

   </div>
{% endblock content %}

shosho/templates/shosho/post_edit.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
   <div class="container">
        <div class="row mt-5">
            <div class="col-md-5 col-sm-6">
                <a href="{% url 'post-detail' object.id %}" class="btn btn-light"> Back to Post</a>
            </div>
        </div>
       <div class="row justify-content-center mt-3">
           <div class="col-md-5 col-sm-12 border-bottom">
               <h4>Update Your Post</h4>
           </div>
       </div>

       <div class="row justify-content-center mt-3">
           <div class="col-md-5 col-sm-12 border-bottom">
                   <form action="" method="POST" enctype="multipart/form-data">
                       {% csrf_token %}
                       {{form | crispy}}
                       <div class="d-grid gap-2">
                           <button class='btn btn-dark mt-4 mb-4'>Submit</button>
                       </div>
                   </form>
           </div>
       </div>

   </div>
{% endblock content %}

shosho/templates/shosho/post_list.html
 {% extends 'landing/base.html' %}
 {% load crispy_forms_tags %}

 {% block content %}
    <div class="container">
        <div class="row justify-content-center mt-3">
            <div class="col-md-5 col-sm-12 border-bottom">
                <h4>Add a Post</h4>
            </div>
        </div>

        <div class="row justify-content-center mt-3">
            <div class="col-md-5 col-sm-12 border-bottom">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form | crispy}}
                        <div class="d-grid gap-2">
                            <button class='btn btn-dark mt-4 mb-4'>Submit</button>
                        </div>
                    </form>
            </div>
        </div>

        {% if post_list.all.count > 0 %}
        {% for post in post_list %}
        <div class="row justify-content-center mt-3">
            <div class="col-md-8 col-sm-12 border-bottom ">
                {% if post.shared_user %}
                <div>
                    <a href="{% url 'profile' post.shared_user.profile.pk %}">
                    <img class = "rounded-circle post-img" src="{{post.shared_user.profile.picture.url}}" alt="Image">
                    </a>
                    <p class="post-text">
                        <a class="text-primary link-color" href="{% url 'profile' post.shared_user.profile.pk %}">
                        @{{post.shared_user}}</a> shared a post on  {{post.shared_on}}
                    </p>
                </div>
                
                
                {% else %}
                
                <div>
                    <a href="{% url 'profile' post.author.profile.pk %}">
                    <img class = "rounded-circle post-img" src="{{post.author.profile.picture.url}}" alt="Image">
                    </a>
                    <p class="post-text">
                        <a class="text-primary link-color" href="{% url 'profile' post.author.profile.pk %}">
                        @{{post.author}}</a>  {{post.created_on}}
                        <span onclick="shareToggle('{{post.pk}}')"><i class="fa-solid fa-share-from-square share-btn"></i></span>
                    </p>
                </div>
                {% endif %}
                <form action="{% url 'share-post' post.pk %}" method="POST" class='d-none' id="{{post.pk}}">
                    {% csrf_token %}
                    {{ share_form | crispy }}
                    <div class="d-grid gap-2">
                        <button class="btn btn-dark mt-3"> Share Post..</button>
                    </div>
                </form>

                {% if post.shared_body %}
                <div class="position-relative border-bottom mb-3 body">
                    <p>{{post.shared_body}}</p>
                    </div>

                 <div class="shared-post">
                    <a href="{% url 'profile' post.author.profile.pk %}">
                        <img class = "rounded-circle post-img" src="{{post.author.profile.picture.url}}" alt="Image">
                        </a>
                        <p class="post-text">
                            <a class="text-primary link-color" href="{% url 'profile' post.author.profile.pk %}">
                            @{{post.author}}</a>  {{post.created_on}}
                            {% comment %} <span onclick="shareToggle('{{post.pk}}')"><i class="fa-solid fa-share-from-square share-btn"></i></span> {% endcomment %}
                        </p>
                </div> 
                {% endif %}
                    <div class="position-relative">
                        {% if post.image.count > 0 %}
                        <div class="row">
                            {% for img in post.image.all %}
                                <div class="col-md-4 col-xs-12">
                                    <img src=" {{ img.image.url }} " class="post-image" />
                                </div>
                            {% endfor %}
                        </div>
                        {% endif %}

                    <div class="body">
                        <p>{{post.body}}</p>
                    </div>
               <a href="{% url 'post-detail' post.id %}" class="stretched-link"></a>
            </div>

            <div class="d-flex flex-row">
                <form action="{% url 'like' post.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="fa-solid fa-thumbs-up"> <span>{{post.likes.all.count}}</span>  </i>
                    </button>
                </form>

                <form action="{% url 'dislike' post.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="fa-solid fa-thumbs-down"> <span>{{post.dislikes.all.count}}</span> </i>
                    </button>
                </form>
            </div>
       </div>
        </div>
        {% endfor %}
        {% else %}
        <div class='my-5' style='color:grey;'>
            <h3>Check the Menu Page and Click Explore to view other posts</h3>
        </div>
        {% endif %}
    </div>
 {% endblock content %}

shosho/templates/shosho/profile_edit.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
   <div class="container">
        <div class="row mt-5">
            <div class="col-md-5 col-sm-6">
                <a href="{% url 'profile' object.pk %}" class="btn btn-light"> Back to Profile</a>
            </div>
        </div>
       <div class="row justify-content-center mt-3">
           <div class="col-md-5 col-sm-12 border-bottom">
               <h4>Update Your Profile</h4>
           </div>
       </div>

       <div class="row justify-content-center mt-3">
           <div class="col-md-5 col-sm-12 border-bottom">
                   <form action="" method="POST" enctype="multipart/form-data">
                       {% csrf_token %}
                       {{form | crispy}}
                       <div class="d-grid gap-2">
                           <button class='btn btn-dark mt-4 mb-4'>Submit</button>
                       </div>
                   </form>
           </div>
       </div>

   </div>
{% endblock content %}

shosho/templates/shosho/search.html
{% extends 'landing/base.html' %}

{% block content %}

<div class="container">
    <div class="row mt-5">
        <div class="col-md-3 col-sm-6 border-bottom">
            <a href="{% url 'post-list' %}" class="btn btn-light">Back to Feed</a>
        </div>
    {% for profile in profile_list %}
        <div class="row justify-content-center mt-3">
            <div class="col-md-5 col-sm-12 border-bottom position-relative">
                <div>
                    <a href="{% url 'profile' profile.pk %}">
                        {% if profile.picture %}
                    <img class = "rounded-circle post-img" src="{{profile.picture.url}}" alt="Image">
                    {% endif %}
                    </a>
                    <p class="post-text">
                        <a class="text-primary link-color" href="{% url 'profile' profile.pk %}">
                        @{{profile.user}}</a> 
                    </p>
                </div>
                
                {% if profile.location %}
                    <p>{{profile.location}}</p>
                {% endif %}
                <p>Followers: {{profile.followers.all.count}}</p>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock content %}

shosho/templates/shosho/thread.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="card col-md-12 mt-5 p-3 shadow-sm">
			{% if thread.receiver == request.user %}
				<h5>@{{ thread.user }}</h5>
			{% else %}
				<h5>@{{ thread.receiver }}</h5>
			{% endif %}
		</div>
	</div>

	{% if message_list.all.count == 0 %}
	<div class="row my-5">
		<div class="col-md-12">
			<p class="empty-text">No Messages</p>
		</div>
	</div>
	{% endif %}

	{% for message in message_list %}
	<div class="row">
		{% if message.sender_user == request.user %}
		<div class="col-md-12 my-1">
			{% if message.image %}
			<div class="sent-image ms-auto">
				<img src="{{ message.image.url }}" class="message-image" />
			</div>
			{% endif %}
			<div class="sent-message my-3">
				<p>{{ message.body }}</p>
			</div>
		</div>

			{% elif message.receiver_user == request.user %}
			<div class="col-md-12 my-1">
				{% if message.image %}
				<div class="message-receiver-container ms-auto">
					<img src="{{ message.image.url }}" class="message-image" />
				</div>
				{% endif %}
				<div class="received-message my-3">
					
					<p>{{ message.body }}</p>
				</div>
			</div>
			{% endif %}
		</div>
	{% endfor %}

	<div class="row">
		<div class="card col-md-12 p-3 shadow-sm">
			<form method="POST" action="{% url 'create-message' thread.pk %}" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form | crispy }}

				<div class="d-grid gap-2 mt-3">
					<button class="btn btn-light" type="submit">Send Message</button>
				</div>
			</form>
		</div>
	</div>
</div>


{% endblock content %}